#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jan  6 12:22:59 2019

@author: vaidehee_barde
"""

#function to rotate the array on the left

def rotateArrayOnLeft(arr,n,d):
    for i in range(d):
        rotateArrayByOne(arr,n)
        
#function to rotate the array by one on the left
def rotateArrayByOne(arr, n):
    temp=arr[0]
    for i in range(n-1):
        arr[i]=arr[i+1]
    arr[n-1]=temp
    
#function to print the array
def printArray(arr,n):
    for i in range(n):
        print("%d" %arr[i], end=" ")
    print("")
    
#test function
arr = [8,3,5,6,7]
n = len(arr)
printArray(arr,n)
rotateArrayOnLeft(arr, n, 2)
printArray(arr,n)

#output
8 3 5 6 7 
5 6 7 8 3 
