#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jan  6 13:10:02 2019

@author: vaidehee_barde
"""

def reverseArray(arr):
    start=0
    end=len(arr)-1
    while start<end:
        temp=arr[start]
        arr[start]=arr[end]
        arr[end]=temp
        start+=1
        end-=1
        
def printArray(arr):
    for i in range(len(arr)):
        print(arr[i], end=" ")
        
arr=[1,2,3,4,5]
reverseArray(arr)
printArray(arr)