#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jan  6 18:22:03 2019

@author: vaidehee_barde
"""

CONST_MAX=500
arr=[1,2,56,12,4,15]
total=16
map1=[0]*CONST_MAX
for i in range(len(arr)):
    temp=total-arr[i]
    if (temp>0 and map1[temp]==1):
        print(temp, arr[i])
    else:
        map1[arr[i]]=1
        
#output
#12 4
#1 15
